// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8q-CM2F1oIz8ANp93GM3A0B1jgsnWs84',
    appId: '1:247982414999:web:cda640d7189e25e6349dd2',
    messagingSenderId: '247982414999',
    projectId: 'signin-47c52',
    authDomain: 'signin-47c52.firebaseapp.com',
    storageBucket: 'signin-47c52.appspot.com',
    measurementId: 'G-MFHZKMKPFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtPsHkEY4BkxfUQS8peMrkIMVaxn2lv6w',
    appId: '1:247982414999:android:b92e0ce2917f2f51349dd2',
    messagingSenderId: '247982414999',
    projectId: 'signin-47c52',
    storageBucket: 'signin-47c52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDL2qzIR7LON0yeXj3ZzujRI5Gwb_teL2A',
    appId: '1:247982414999:ios:e3154e5ae0eeb100349dd2',
    messagingSenderId: '247982414999',
    projectId: 'signin-47c52',
    storageBucket: 'signin-47c52.appspot.com',
    androidClientId: '247982414999-gds164gls314mo32odt686tvfd0a8rji.apps.googleusercontent.com',
    iosClientId: '247982414999-73mu3n3tuv6pidnfo0knj02co96qdfk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasiya',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDL2qzIR7LON0yeXj3ZzujRI5Gwb_teL2A',
    appId: '1:247982414999:ios:e3154e5ae0eeb100349dd2',
    messagingSenderId: '247982414999',
    projectId: 'signin-47c52',
    storageBucket: 'signin-47c52.appspot.com',
    androidClientId: '247982414999-gds164gls314mo32odt686tvfd0a8rji.apps.googleusercontent.com',
    iosClientId: '247982414999-73mu3n3tuv6pidnfo0knj02co96qdfk6.apps.googleusercontent.com',
    iosBundleId: 'com.example.nasiya',
  );
}
